(function(){var d=void 0,g=true,h=null,j=false;function k(){return function(){}}function l(a){return function(){return this[a]}}function n(a){return function(){return a}}var o,q=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ca(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function r(a,b,c){r=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ca:da;return r.apply(h,arguments)}function ea(a,b){function c(){}c.prototype=b.prototype;a.pa=b.prototype;a.prototype=new c;a.prototype.constructor=a};function fa(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function ga(a,b){var c="",e=ha(encodeURIComponent(a));e.splice(b||5,e.length);s(e,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",e;a>0;)e=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(e)+b,a>>>=6;a=b}c+=a});return c}
function ha(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,e=4023233417,f=2562383102,i=271733878,p=3285377520,C=[],m,L,H,P,S,ba=Math.ceil((a.length/4+2)/16),Y=[ba],N=0,I;N<ba;N++){Y[N]=[];for(m=0;m<16;m++)Y[N][m]=a.charCodeAt(N*64+m*4)<<24|a.charCodeAt(N*64+m*4+1)<<16|a.charCodeAt(N*64+m*4+2)<<8|a.charCodeAt(N*64+m*4+3)}N=(a.length-1)*8;a=ba-1;Y[a][14]=Math.floor(N/Math.pow(2,32));Y[a][15]=N&4294967295;for(N=0;N<ba;N++){for(I=0;I<16;I++)C[I]=Y[N][I];
for(I=16;I<80;I++)C[I]=(C[I-3]^C[I-8]^C[I-14]^C[I-16])<<1|(C[I-3]^C[I-8]^C[I-14]^C[I-16])>>>31;a=c;m=e;L=f;H=i;P=p;for(I=0;I<80;I++)S=Math.floor(I/20),S=(a<<5|a>>>27)+(S==0?m&L^~m&H:S==1?m^L^H:S==2?m&L^m&H^L&H:m^L^H)+P+b[S]+C[I]&4294967295,P=H,H=L,L=m<<30|m>>>2,m=a,a=S;c=c+a&4294967295;e=e+m&4294967295;f=f+L&4294967295;i=i+H&4294967295;p=p+P&4294967295}return[c,e,f,i,p]}
function ia(a){var b=q.navigator,c=q.window.screen,e=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];s(b.plugins,function(a){e.push(a.name+a.description+a.filename+a[0].type)});b=q.performance;e=e.concat([b&&b.now?b.now():"",document.title,q.location.href,t(),fa()]);return e.concat(a||[]).join()}function u(a,b,c){var e=Array.prototype.slice,f=e.call(arguments,2);return function(){return a.apply(b,f.concat(e.call(arguments)))}}
function v(a){return typeof a!=="undefined"}function ja(a){return a.replace(/^www\./,"")}function w(a,b,c,e){a.addEventListener?a.addEventListener(b,c,!!e):a.attachEvent&&a.attachEvent("on"+b,c)}function ka(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function x(a){return typeof a==="number"}function la(a){return typeof a==="string"}function ma(a){return typeof a==="function"}
function na(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function t(){return(new Date).getTime()}function oa(a){return encodeURIComponent(a)}function s(a,b){if((!!a&&a.constructor===Object)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var e=a.length;c<e;c++)if(b(a[c],c)===j)break}}function pa(a,b){for(var c=0,e=a.length;c<e;c++)if(b(a[c]))return c;return-1}function qa(a){var b=q.pSUPERFLY_video,a=pa(b,a);if(a>-1)return b[a]}
function ra(a){return a===d?0:t()-a}function sa(a,b){var c,e,f="c"+Math.round(Math.random()*1E9);e=250;a+=(a.indexOf("?")>-1?"&":"?")+(c||"callback")+"=_cb_call."+f;c=document.createElement("script");var i=ta(f,c);c.id=f;c.type="text/javascript";c.charset="UTF-8";c.src=a;var p=document.getElementsByTagName("head");if(p=p&&p[0]){var C=q._cb_call||(q._cb_call={});e=setTimeout(ua(b,i),e);C[f]=va(b,i,e);p.appendChild(c)}}function ua(a,b){return function(){b();a(d,"TIMEOUT")}}
function va(a,b,c){return function(e){b(c);a(e)}}function ta(a,b){return function(c){c&&clearTimeout(c);setTimeout(function(){b&&b.parentNode&&b.parentNode.removeChild(b)},0);var e=q._cb_call,f=j;if(e&&(c?delete e[a]:e[a]=wa,s(e,function(){f=g;return j}),!f))try{delete q._cb_call}catch(i){q._cb_call=d}}}function wa(){}
function xa(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],e=0,f=b.length;e<=f;e++)c[e]=[e];for(var i=0,p=a.length;i<=p;i++)c[0][i]=i;for(var C,m,L,e=1;e<=f;e++)for(i=1;i<=p;i++)C=e-1,m=i-1,L=c[C][m],b.charAt(C)==a.charAt(m)?c[e][i]=L:(m=c[e][m]+1,C=c[C][i]+1,L+=2,c[e][i]=Math.min(m,C,L));return c[b.length][a.length]}function ya(a){return a===d?0:t()-a}function za(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}
var Aa,Ba=q.setInterval,Ca=q.clearInterval,Da=q.setTimeout,Ea=q.clearTimeout;function Fa(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),s(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function Ga(a,b){var c="",e=q.location.href.split("?");if(e.length){var e=Fa(e[1]),f=b||a;e[f]&&(c=e[f])}return c}function Ha(a,b){return!b?g:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Ia(a){var b=[];s(Ja,function(c){var e=a[c];v(e)&&(Object.prototype.toString.call(e)==="[object Array]"?s(e,function(a){b.push(c+"="+a)}):e&&e.constructor===Object?s(e,function(a,c){b.push(c+"="+a)}):((e+"").length||c=="r")&&b.push(c+"="+e))});b.push("_");return b.join("&")}
function Ka(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),e=q.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=e.protocol+a;else if(a.indexOf("/")===0)var f=Ha(e.protocol,e.port)?"":e.port,a=e.protocol+"//"+e.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||e.href,i=f.indexOf("?");i===-1&&(i=f.indexOf("#"));if(i===-1)i=f.length;i=f.lastIndexOf("/",i);a=i===-1?"/"+a:f.substr(0,i)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=e.hostname;if(b.protocol==="")b.protocol=e.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Ha(b.protocol,b.port)||b.port==="0")b.port="";return b}
function La(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function y(a,b,c){a[b]=a[b]||c}function Ma(a,b){for(var c=q[a]||[];c.length;)b(c.shift());q[a]={push:b}}function Na(a){s(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=Fa(b.src.split("?")[1]),y(a,"uid",b.uid),y(a,"domain",b.domain),j})}function Oa(a,b){return a[b]?encodeURIComponent(a[b]):""}function Pa(a){var b={};s(a,function(a,e){e.charAt(0)=="_"&&(b[e]=a)});return b};function Qa(a,b){var c,b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");var e=[];c=c.getElementsByTagName(b);for(var f=c.length;f--;)c[f].getAttribute(a)&&e.push(c[f]);return e}function Ra(a,b,c){return a===d?j:c===d&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?j:Ra(a.parentNode,b,c)}
function Sa(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=Qa("data-cb-scroll-element"))&&a.length)return a[0][c];if(x(q[b]))return q[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function Ta(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function Ua(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function Va(a,b,c){var e=a.ownerDocument.documentElement,f=0,i=v(c)?c+1:-1;la(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==e&&f!==i;){if(c(a))return a;a=a.parentNode;f++}return h}function Wa(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function Xa(a){a=a||window.event;return!a?h:Va(a.target||a.srcElement,Wa,10)}function Ya(a,b){var c=document.createElement(a);s(b,function(a,b){c.setAttribute(b,a)});return c};var Za,$a,ab;
function bb(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);cb();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=v(d)?d:{},b.src=a,a=Ya("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],v(d)?d.appendChild(a):b&&b.appendChild(a)}}
function cb(){Ea($a);$a=d;ka(q,"message",bb);ab&&ab.parentNode&&ab.parentNode.removeChild(ab);ab=d};var z={};z.Y=function(a){var b=q._sf_async_config;if(!a&&b&&b.noCookies)return h;if(z.Y.tb!==d)return z.Y.tb;var a=t()+"",c,e;try{if((e=q.localStorage).setItem(a,a),c=e.getItem(a)===a,e.removeItem(a),c)return z.Y.tb=e}catch(f){}return z.Y.tb=h};z.D=function(a){var b=z.Y();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&t()>c)?(z.remove(a),""):b.getItem(a)||""};
z.create=function(a,b,c){var e=z.Y();if(e){var f=new Date;f.setTime(t()+c*1E3);try{e.setItem(a,b),e.setItem(a+"_expires",f.getTime())}catch(i){}}};z.remove=function(a){var b=z.Y();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function db(){var a=q._sf_async_config&&q._sf_async_config.domain;if(a&&!Za){Za=g;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);w(q,"message",bb);$a=Da(cb,1E4);var b=v(d)?d:{};b.src=a;a=Ya("iframe",b);a.style.display="none";v(d)?d.appendChild(a):document.body&&document.body.appendChild(a);ab=a}}
function eb(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=z.Y(g),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),db(),ka(q,"message",eb))}};function fb(){this.na={};this.Na=1}function A(a,b,c,e){a.Na++;a.na[b]=a.na[b]||{};a.na[b][a.Na]=[c,e];return a.Na}function gb(a,b){if(la(b))a.na[b]=d,delete a.na[b];else if(x(b)){var c=g;s(a.na,function(a){s(a,function(f,i){if(parseInt(i,10)===b)return a[i]=d,delete a[i],c=j});return c})}}fb.prototype.Da=function(a,b){if(this.na[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];s(this.na[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
fb.prototype.addEventListener=function(a,b){var c=A(this,a,b);b._cbEventId=c};fb.prototype.removeEventListener=function(a,b){this.na[a]&&this.na[a][b._cbEventId]&&this.na[a][b._cbEventId][0]===b&&gb(this,b._cbEventId)};var B=new fb;var D={};
D.N=function(){D.Ab?D.gb("pageload"):(D.Dc=[{target:q,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:q,event:"resize"},{target:document.body,event:"mousedown"}],D.lb=h,D.Rb=j,D.Ra=h,D.ic={},D.pb={},s(D.Dc,function(a){var b=a.event;w(a.target,b,function(a){D.gb.call(D,b,a)})}),A(B,"f",function(){D.gb("focus")}),D.gb("pageload"),w(document.body,"click",function(a){(a=Xa(a))&&B.Da("c",a)},g),w(document.body,"contextmenu",function(a){(a=Xa(a))&&
B.Da("r",a)}),D.Ab=g)};D.Ic=function(){var a,b=D.ic.keydown;if(b===d)return j;b=t()-b;return b<=(a||15E3)&&b>=0};D.Qa=function(a,b){var c=D.pb[a];if(!c)return"";var b=b||t(),e,f=0;s(c,function(a){e=Math.floor((b-a)/1E3);e>=0&&e<16&&(f|=1<<e)});c=("0000"+f.toString(16)).slice(-4);return c=="0000"?"":c};D.Ed=function(){D.pb={}};D.Zb=100;D.gb=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}D.Jd(a);D.lb===h?D.wc():D.Rb=g};
D.Jd=function(a){var b=t();D.ic[a]=b;var c=D.pb[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();D.pb[a]=c};D.wc=function(){D.lb=Da(D.Oc,D.Zb);B.Da("a");D.Ra!==h&&Ea(D.Ra);D.Ra=Da(function(){B.Da("i");Ea(D.Ra);D.Ra=h},5E3+D.Zb)};D.Oc=function(){Ea(D.lb);D.lb=h;if(D.Rb)D.Rb=j,D.wc()};var hb,ib,jb,kb,lb;(function(){var a,b;s(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof q.document[a]==="boolean")return b=c,j});b!==d&&(kb=a,lb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),jb=b+"visibilitychange")})();var mb=j;function nb(){mb=lb&&q.document[lb]==="prerender"?g:j}function ob(){ib=g;B.Da("f")}function pb(){ib=j;B.Da("b")}
function qb(a,b,c){q.addEventListener?q.addEventListener(a,c,j):q.document.attachEvent&&q.document.attachEvent(b,c)}function rb(){var a=g;q.document.hasFocus&&(a=q.document.hasFocus());var b=j;kb&&(b=q.document[kb]);return a&&!b}function sb(){rb()?ob():pb()}function tb(a){nb();if(mb){var b=j,c=function(){b||(nb(),mb||(b=g,a(),q.window.setTimeout(function(){q.document.removeEventListener(jb,c,j)},100)))};q.document.addEventListener(jb,c,j)}else a()};function ub(){this.k=q._sf_async_config||{};this.cc=u(this.pc,this)}ub.prototype.N=function(){this.rc=0};ub.prototype.pc=k();ub.prototype.Xa=function(a){if(!mb){var b=this.cc,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};ub.prototype.xa=function(){this.cc=h};var E={};E.Lc=function(){try{E.create("_cb_test","1",1);var a=E.D("_cb_test");E.remove("_cb_test");return a==="1"}catch(b){return j}};E.D=function(a){a+="=";var b="";s(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
E.create=function(a,b,c){var e=q._sf_async_config;if(e&&e.noCookies)return"";e=new Date;e.setTime(t()+c*1E3);a=a+"="+b+("; expires="+e.toGMTString())+"; path=/";return document.cookie=a};E.remove=function(a){return E.D(a)?E.create(a,"",-86400):""};function vb(a){this.ib=a||"";this.Pc=z.Y()!==h||E.Lc();this.Qb=j;wb(this)}o=vb.prototype;o.isSupported=l("Pc");
function wb(a){if(!E.D("_cb_ls")){var b=z.Y()!==h,c=E.D("_SUPERFLY_nosample");c&&s(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_nosample",c,600,g)});var e=E.D("_chartbeat3");e&&(a.create("_v__chartbeat3",e,2592E3,g),E.remove("_chartbeat3"));b&&((b=E.D("_chartbeat2"))&&a.create("_chartbeat2",b,63072E3,g),(b=E.D("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,63072E3,g),(b=E.D("_chartbeat5"))&&a.create("_chartbeat5",b,60,g));E.create("_cb_ls","1",2592E3)}}
function xb(a){var b=a.Qb;a.Qb=j;return b}o.create=function(a,b,c,e){a=e?a:this.ib+a;(z.Y()?z:E).create(a,b,c);z.Y()&&E.create(a,b,c)};o.update=function(a,b,c,e,f,i,p){a=e?a:this.ib+a;f=la(f)?f:"::";e=(e=this.D(a,g))?e.split(f):[];if(p&&e.length){var C=p(b),m=pa(e,function(a){return p(a)===C});m!==-1&&e.splice(m,1)}x(i)&&e.length>=i&&e.splice(0,e.length-i+1);e.push(b);this.create(a,e.join(f),c,g)};
o.D=function(a,b){var a=b?a:this.ib+a,c=(z.Y()?z:E).D(a);if(!c&&z.Y()&&(c=E.D(a))&&E.D("_cb_ls")){this.Qb=g;var e;switch(a){case "_SUPERFLY_nosample":e=600;break;case "_chartbeat4":e=3600;break;case "_cb_cp":e=3600;break;case "_chartbeat3":e=2592E3;break;default:e=63072E3}z.create(a,c,e)}return c};o.remove=function(a,b){a=b?a:this.ib+a;(z.Y()?z:E).remove(a);z.Y()&&E.remove(a)};function yb(a){var b=h;if(a&&(b=zb()))return b;var c=q.location,b=Ab(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),e=/&utm_[^=]+=[^&]+/ig;(c=e.exec(c.search))&&(a=a.replace(e,""));e=/\?utm_[^=]+=[^&]+(.*)/i;(c=e.exec(a))&&(a=a.replace(e,c[1]!=""?"?"+c[1]:""));return b+a}function zb(){var a=h;s(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=Ka(b.href),a=Ab(b.pathname)+b.search+b.hash,j});return a}
for(var Bb={},Cb=0;Cb<81;Cb++)Bb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Cb)]=g;function Db(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Bb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function Ab(a){if(!la(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Db);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};var F={Fc:{IDLE:0,Nd:1,Md:2,Ec:3},oa:0};F.N=function(){if(!F.Ab)A(B,"a",F.Sc,F),A(B,"i",F.Vc,F),A(B,"f",F.Uc,F),A(B,"b",F.Tc,F),F.Ab=g};F.H=function(){return F.oa};F.Sc=function(){F.oa===1?F.Aa(3):F.oa===0&&F.Aa(2)};F.Vc=function(){F.oa===3?F.Aa(1):F.oa===2&&F.Aa(0)};F.Uc=function(){(F.oa===0||F.oa===2)&&F.Aa(3)};F.Tc=function(){F.oa===3?F.Aa(2):F.oa===1&&F.Aa(0)};F.Aa=function(a){F.oa=a;B.Da("s",a)};function Eb(a,b){this.yb=a||d;this.Fb=b||d;this.Sa=this.Ma=0;this.zb=u(this.zb,this)}o=Eb.prototype;o.N=function(){this.Sa=this.Ma=0;this.Za=h;this.Fd=A(B,"s",this.hc,this);this.hc(F.H())};o.hc=function(a){Ca(this.Za);this.Za=h;if(a===F.Fc.Ec)this.Za=Ba(this.zb,1E3)};o.zb=function(){if(this.yb===d||this.yb())this.Ma++,this.Sa++,this.Fb&&this.Fb()};o.terminate=function(){Ca(this.Za);this.Za=h;gb(B,this.Fd)};o.xa=function(){this.terminate();this.Fb=this.yb=d};function G(){ub.call(this);this.Fa=[];this.G=new vb(this.xc);this.ma=new Eb;this.Hb=u(this.Va,this);w(q,"unload",this.Hb);tb(u(this.N,this))}ea(G,ub);o=G.prototype;o.Nb=g;
o.N=function(){G.pa.N.call(this);this.eb=this.Ia=0;this.Ba=t();this.La=ga(Fb(this));var a=(this.G.D("_chartbeat2",g)||"").split("."),b=t(),c=b-+(a[1]||0);b-=+(a[2]||0);this.Db=a[0]&&c>18E5&&b<2592E6?0:1;this.Lb=g;this.Ua=72E5;if(this.Nb&&(a=+this.k.sessionLength,!isNaN(a)))this.Ua=a*6E4;a=(this.G.D("_chartbeat2",g)||"").split(".");a.length>4&&(a=[]);var c=t(),e="1",f=a&&+a[2],b=a&&a[3];if(a&&f&&b)if(e=Math.abs((na(c)-na(f))/864E5)){e=Math.min(e,16)-1;for(f="";e--;)f+=0;e=(b+f+"1").slice(-16)}else e=
b;b=e;a[0]||(a[0]=this.k.utoken||ga(Fb(this),3),a[1]=c);a[2]=c;a[3]=b;this.ob=a[0];this.Bd=a.join(".");this.G.create("_chartbeat2",this.Bd,63072E3,g);this.k.utoken=this.ob;var i;c=+a[1];b=+a[2];if((a=a[3])&&c&&b)i=(Math.min((Math.abs((na(b)-na(c))/864E5)||0)+1,16,a.length)-1).toString(16),i+=("0000"+parseInt(a,2).toString(16)).slice(-4);this.gc=i;this.ma.N();F.N();D.N();hb||(ib=rb(),jb&&q.document.addEventListener&&q.document.addEventListener(jb,sb,j),qb("focus","onfocusin",ob),qb("blur","onfocusout",
pb),ib&&ob(),hb=g);this.Ta=0;this.Hc=A(B,"a",this.cd,this)};function Gb(a){if(!a.G.D("_SUPERFLY_nosample")&&!mb)a.bd?a.kb():(a.bd=g,!q._sf_async_config&&!q._cbq?(a.hb=u(a.kb,a),w(q,"load",a.hb)):a.kb())}o.kb=function(){var a=q._sf_startpt,b=q._sf_endpt;if(x(a))this.Wa=x(b)?b-a:t()-a;D.N();a=u(this.ka,this);this.ya=Ba(a,15E3);this.ka()};
o.ka=function(){var a=this.ma.Sa,a=this.k.reading&&+this.k.reading||a>0;if(this.eb<this.Ia&&!a)this.eb++;else{var b;if(Aa===d)b=q.navigator.userAgent,Aa=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Aa;b&&!a?this.eb++:(a?this.Ia=0:this.sb(),this.eb=0,this.Fa.push(0),this.Fa.length>18&&this.Fa.shift(),this.Nb&&t()-this.Ba>=this.Ua?this.terminate():this.Ka())}};
o.pc=function(){this.Fa.push(1);var a=0;s(this.Fa,function(b){a+=b});a<3?(this.Lb=g,this.sb()):(this.terminate(),this.G.create("_SUPERFLY_nosample","1",600))};o.Va=k();o.cd=function(){var a=Hb(this);this.Ta=Math.max(this.Ta,a)};function Hb(a){return Sa(!!a.k.scrollElement)}o.sb=function(){var a=this.Ia;this.Ia=a=a?Math.min(a*2,16):1};o.Ld=function(a,b){if(!mb)this.Va(),this.terminate(),this.Vb=q.location.protocol+"//"+this.k.domain+this.k.path,this.k.path=Ab(a),b&&(this.k.title=b),this.N(),Gb(this)};
function Ib(a){if(a.Vb)return g;a=(document.referrer||"").indexOf("://"+q.location.hostname+"/");return a!=-1&&a<9}function Jb(a){a=a.Vb;if(!a&&(a=document.referrer||"")){var b=Ka(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=Ab(b.pathname),a=La(b)}return encodeURIComponent(a)}function Kb(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function Fb(a){a=[Jb(a),Ua("Width"),Ua("Height")];return ia(a)}
function Lb(a){var b=[],c=a.G.D("_chartbeat4");c&&(s(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.G.remove("_chartbeat4"));return b}o.terminate=function(){this.ma.terminate();gb(B,this.Hc);this.hb!==d&&ka(q,"load",this.hb);Ca(this.ya)};o.xa=function(){this.terminate();ka(q,"unload",this.Hb);this.Hb=this.hb=this.G=this.Fa=this.k=h;this.ma.xa();this.ma=h;G.pa.xa.call(this)};function Mb(a){var b=a.offsetLeft,c=a.offsetTop,e=Nb(a);b+=e.x;c+=e.y;for(var f=j,e=a.offsetParent;a&&a!==d&&a!==document.body;){if(a===e)e=Nb(a),b+=a.offsetLeft+e.x,c+=a.offsetTop+e.y,e=a.offsetParent;if(Ob(a,["position"]).position==="fixed"){f=g;break}a=a.parentElement}f&&(b+=0,c+=0);return{x:b,y:c}}
function Ob(a,b){var c={},e,f;q.getComputedStyle?e=q.getComputedStyle(a,h):a.currentStyle?f="currentStyle":a.style&&(f="style");s(b,function(b){c[b]=e?e[b]||e.getPropertyValue(b):a[f][b]});return c}var Pb=/matrix(3d)?\((.*)\)/;function Nb(a){var b={x:0,y:0},a=Ob(a,["transform"]).transform;if(!la(a))return b;var c=a.match(Pb);if(!c)return b;var a=c[2].split(", "),e;v(c[1])?(c=12,e=13):(c=4,e=5);b.x=parseInt(a[c],10);b.y=parseInt(a[e],10);return b};function Qb(a,b){for(var c=b||document.documentElement,e=[],f=h,i=a,p,C,m,L,H,P;i&&i!==c;){p=i.nodeName.toLowerCase();f=i;C=f.nodeName;if((i=i.parentNode)&&i!==document.documentElement){m=i.children;L=0;for(H=0,P=m.length;H<P;H++){if(f===m[H]){p+="["+(1+H-L)+"]";break}m[H].nodeName!==C&&L++}}e.unshift(p)}return e.join("/")};function J(){"postMessage"in window&&w(q,"message",u(this.Wc,this));G.call(this);Ma("_cbq",u(this.uc,this))}ea(J,G);J.prototype.N=function(){J.pa.N.call(this);this.rb=h;Na(this.k);var a=q.location;y(this.k,"pingServer","ping.chartbeat.net");y(this.k,"title",document.title);y(this.k,"domain",a.hostname);this.k.path=this.k.path?Ab(this.k.path):yb(!!this.k.useCanonical);this.ra=ja(a.hostname);this.k.domain=ja(this.k.domain);this.Jc=A(B,"c",this.hd,this);this.Kc=A(B,"r",this.jd,this);this.Ha=h};
J.prototype.Gc=function(a){this.rb=a};J.prototype.Va=function(){this.G.update("_chartbeat4",["t="+this.La,"E="+this.ma.Ma,"x="+Hb(this),"c="+Math.round((t()-this.Ba)/600)/100,"y="+Ua("Height"),"w="+Ta()].join("&"),3600,d,d,1)};var Ja="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR".split(",");o=J.prototype;
o.Ka=function(a){this.rc++;var b={};b.g=this.k.uid;b.g0=Oa(this.k,"sections");b.g1=Oa(this.k,"authors");b.g2=Oa(this.k,"zone");b.g3=Oa(this.k,"sponsorName");b.g4=Oa(this.k,"type");!this.k.noCookies&&this.G.isSupported()?b.n=this.Db:b.nc=1;b.c=Math.round((t()-this.Ba)/600)/100;b.E=this.ma.Ma;var c=Hb(this);this.Ta=Math.max(this.Ta,c);b.x=c;b.m=this.Ta;b.y=Ua("Height");b.o=Ua("Width");b.w=Ta();b.b=this.Wa?this.Wa:"";if(this.gc)b.f=this.gc;b[""]=Pa(this.k);b.t=this.La;b.V=61;b.tz=(new Date).getTimezoneOffset();
b.sn=this.rc;c=this.ma.Sa;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.ob;b.d=encodeURIComponent(this.ra);b.j=Math.round((this.Ia+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var e=b.c*6E4+this.Ba;b.eD=D.Qa("mousedown",e);b.eM=D.Qa("mousemove",e);b.eK=D.Qa("keydown",e);b.eR=D.Qa("resize",e);b.eS=D.Qa("scroll",e);D.Ed();D.Ic()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Ib(this);if(this.Lb)this.Lb=j,c?this.Ha=Rb(this):b.r=Jb(this),b.i=Kb(this),e=
this.k.hudTrackable,e!==d&&(b.L=e?"1":"0"),this.k.alias&&(b.PA=encodeURIComponent(this.k.alias));if(c){if(this.Ha){if(b.v=encodeURIComponent(this.Ha.path),b.K=Sb(this.Ha),this.Ha.Eb>1)b.l1=this.Ha.Eb}else b.v=Jb(this);this.Vb&&(b.vp=1)}b.A=this.rb?this.rb:"";b._c=Ga("utm_campaign",this.k.campaignTag);b._m=Ga("utm_medium",this.k.mediumTag);b.z=Lb(this);b.C=this.k.mobileApp?1:"";b.KK=a?Sb(a,g):"";b.l=xb(this.G)?1:"";this.ma.Sa=0;this.Xa((q.location.protocol||"http:")+"//"+this.k.pingServer+"/ping?"+
Ia(b))};o.Wc=function(a){var b=this.k;if(a.origin==="http://"+(b.playerdomain||this.ra)){var c=a.data;la(c)&&c.indexOf("cbqpush::")===0?(a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.uc(a))):c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+Kb(this)+"&referrer="+Jb(this)+"&internal="+(Ib(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ra)+"&utoken="+this.ob,a.source.postMessage(b,"*"))}};
o.uc=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.Ia=0};function Tb(a){a=a.replace(/-{2,}/g,"-");a=Ka(a);a.pathname=Ab(a.pathname);return a}o.hd=function(a){Ub(this,a,"c")};o.jd=function(a){Ub(this,a,"r")};
function Ub(a,b,c){if(a.Nb&&t()-a.Ba>=a.Ua)a.terminate();else{var e=b.href||"",e=Tb(e);if(!(e.hostname!==q.location.hostname||e.protocol.indexOf("http")!==0)){var e=La(e),f=Va(b,function(a){return a.id}),i=Qb(b,f);f&&(i&&(i="/"+i),i="*[@id='"+f.id+"']"+i);f=ga(i);b=Mb(b);c={left:b.x,top:b.y,path:a.k.path,href:e,Yb:f,Xb:i,Pb:c,Eb:0};a.Ka(c);a.G.update("_chartbeat5",Vb(c),60,j,d,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function Sb(a,b){var c=[a.left,a.top,a.Yb,encodeURIComponent(a.Xb),a.Pb];b&&c.push(encodeURIComponent(a.href));return c.join("::")}function Vb(a){var b=encodeURIComponent(a.Xb),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.Yb,b,a.Pb].join(",")}
function Rb(a){var b=a.G.D("_chartbeat5");if(!b)return h;var c=b.split("::"),b=c.length,e,f;if(b===1)e=c[0].split(","),f=0;else{var i,p=Tb(q.location.href),C=La(p);s(c,function(a,b){var c=a.split(","),p=xa(C,decodeURIComponent(c[3]));if(p===0)return e=c,f=b,j;if(i===d||p<i)i=p,e=c,f=b})}c.splice(f,1);a.G.create("_chartbeat5",c.join("::"),60);(a=e[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:e[0],top:e[1],path:decodeURIComponent(e[2]),Yb:e[4]||"",Xb:a,Pb:e.length>6?e[6]:"c",
Eb:b}}o.terminate=function(){gb(B,this.Jc);gb(B,this.Kc);J.pa.terminate.call(this)};var K="ct",M="s1";function O(a){this.a=a;this.B=this.F=j;this.q=t();this.ia()}o=O.prototype;o.ia=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.ha();this.a.on("play",u(this.ha,this));this.a.ready(u(this.la,this))};o.la=function(){this.ga=this.a.mediainfo;this.F=g};o.ha=function(){this.B=g};o.O=function(){return this.F&&this.J()!==""};
o.wb=function(){var a;this.a.cb_configs&&this.a.cb_configs.domain?a=this.a.cb_configs.domain:!a&&q._sf_async_config&&q._sf_async_config.domain&&(a=q._sf_async_config.domain);return a};o.xb=function(){var a;this.a.cb_configs&&this.a.cb_configs.uid?a=this.a.cb_configs.uid:!a&&q._sf_async_config&&q._sf_async_config.uid&&(a=q._sf_async_config.uid);return a};
o.J=function(){if(!this.ga)this.ga=this.a.mediainfo;return(this.ga&&this.ga.hasOwnProperty("name")?this.ga.name:this.a.el().getAttribute("title"))||""};o.M=function(){if(!this.ga)this.ga=this.a.mediainfo;return(this.ga&&this.ga.hasOwnProperty("id")?this.ga.id:this.a.el().attributes["data-video-id"]&&this.a.el().attributes["data-video-id"].value?this.a.el().attributes["data-video-id"].value:this.a.src())||""};o.U=function(){return K};o.P=n("");o.ca=function(){var a=this.a.duration();return za(a)};
o.H=function(){return!this.B?M:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};o.X=function(){var a=this.a.currentTime();return za(a)};o.T=n(-1);o.ba=function(){if(!this.ga)this.ga=this.a.mediainfo;return(this.ga&&this.ga.hasOwnProperty("thumbnail")?this.ga.thumbnail:this.a.poster())||""};o.Z=k();o.S=k();o.da=function(){return ya(this.q)};
o.$=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.sections?a=this.a.cb_configs.sections.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.sections&&(a=q._sf_async_config.sections.split(","));if(a.length>0&&a[0]!=="")return a};o.Q=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.authors?a=this.a.cb_configs.authors.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.authors&&(a=q._sf_async_config.authors.split(","));if(a.length>0&&a[0]!=="")return a};
o.aa=n("BCN");O.prototype.getStrategyName=O.prototype.aa;O.prototype.isReady=O.prototype.O;O.prototype.getHost=O.prototype.wb;O.prototype.getUid=O.prototype.xb;O.prototype.getTitle=O.prototype.J;O.prototype.getVideoPath=O.prototype.M;O.prototype.getContentType=O.prototype.U;O.prototype.getAdPosition=O.prototype.P;O.prototype.getTotalDuration=O.prototype.ca;O.prototype.getState=O.prototype.H;O.prototype.getCurrentPlayTime=O.prototype.X;O.prototype.getBitrate=O.prototype.T;
O.prototype.getThumbnailPath=O.prototype.ba;O.prototype.getPlayerType=O.prototype.Z;O.prototype.getAutoplayType=O.prototype.S;O.prototype.getViewStartTime=O.prototype.da;O.prototype.getSections=O.prototype.$;O.prototype.getAuthors=O.prototype.Q;O.verify=function(a){return a.controlBar!==d};function Q(a){this.Na=this.ra=d;this.F=j;this.tc=this.ac=-1;this.ta=h;this.a=a;this.B=j;this.Ib=g;this.q=t();this.Jb="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var e=a[c];if((e.indexOf("chartbeat")>=0||e.indexOf("localhost")>=0)&&e.indexOf(".js")>=0){this.Jb=e;break}}if(this.Jb)a=Fa(this.Jb),this.ra=a.domain,this.Na=a.uid;a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);b.getReady()?
this.qc():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,r(this.qc,this))}o=Q.prototype;
o.qc=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.ac=Math.round(a)});b.getCurrentVideo(function(a){c.ta=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,r(this.sd,this));b.addEventListener(a.STOP,r(this.ud,this));b.addEventListener(a.COMPLETE,r(this.kd,this));b.addEventListener(a.BEGIN,r(this.ha,this));this.F=g};o.sd=function(a){this.tc=a.position;this.va=this.Ib=j};o.ud=function(){this.Ib=g};
o.kd=function(){this.va=g};o.ha=function(){this.va=j;if(!this.B)this.B=g};o.O=l("F");o.J=function(){var a="";this.ta&&(a=this.ta.displayName);return a};o.M=function(){var a="";this.ta&&(a="video@"+this.ra+"/"+this.ta.id);return a};o.U=function(){return K};o.P=n("");o.ca=l("ac");o.H=function(){return!this.B?M:this.va?"s4":this.Ib?"s3":"s2"};o.X=l("tc");o.T=n(-1);o.ba=function(){var a="";this.ta&&(a=this.ta.thumbnailURL);return a};o.Z=k();o.da=function(){return isNaN(this.q)?0:ra(this.q)};o.Q=k();
o.$=function(){var a;this.ta&&(a=this.ta.tags);return a};o.S=n("unkn");o.aa=n("BC");o.wb=l("ra");o.xb=l("Na");Q.prototype.isReady=Q.prototype.O;Q.prototype.getTitle=Q.prototype.J;Q.prototype.getVideoPath=Q.prototype.M;Q.prototype.getContentType=Q.prototype.U;Q.prototype.getAdPosition=Q.prototype.P;Q.prototype.getTotalDuration=Q.prototype.ca;Q.prototype.getState=Q.prototype.H;Q.prototype.getCurrentPlayTime=Q.prototype.X;Q.prototype.getBitrate=Q.prototype.T;Q.prototype.getThumbnailPath=Q.prototype.ba;
Q.prototype.getPlayerType=Q.prototype.Z;Q.prototype.getViewStartTime=Q.prototype.da;Q.prototype.getAuthors=Q.prototype.Q;Q.prototype.getSections=Q.prototype.$;Q.prototype.getAutoplayType=Q.prototype.S;Q.verify=function(a){return a===window.brightcove};Q.prototype.getStrategyName=Q.prototype.aa;Q.prototype.getHost=Q.prototype.wb;Q.prototype.getUid=Q.prototype.xb;function R(){this.a=window.flowplayer();this.B=this.F=j;this.q=t();this.ua=this.za=d;this.nb=this.Ya="";this.Cb=d;this.ia()}var Wb=/url\(['"]?([^'"\)]*)['"]?\)/;o=R.prototype;
o.fc=function(){if(this.a.conf&&(this.nb=this.a.conf.title?this.a.conf.title:"",this.Ya=this.a.conf.poster?this.a.conf.poster:"",this.nb&&this.Ya))return g;var a=this.M(),b=Qa("name","param"),c=d;s(b,function(b){if(b.attributes.name&&b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});c===d&&(b=Qa("src","video"),s(b,function(b){if(b.attributes.src.value&&a.indexOf(b.attributes.src.value)!=-1)return c=b,j}));b=Ra(c,"data-swf");if(b===j)return j;var e=b.style.background;if(e){if(e=
e.match(Wb))this.Ya=e[1]}else this.Ya=b.attributes.poster&&b.attributes.poster.value;this.nb=b.title;if(this.Cb!==d)clearInterval(this.Cb),this.F=g;return g};o.ia=function(){this.a.Ud?this.la():this.a.bind("ready",r(this.la,this));this.a.bind("resume",r(this.ha,this));this.a.Td&&this.ha()};o.la=function(){this.fc()===j?this.Cb=setInterval(r(this.fc,this),1E3):this.F=g};o.ha=function(){if(!this.B)this.B=g};o.O=l("F");o.J=l("nb");o.M=function(){return this.a.video.url||this.a.video.src};o.U=function(){return K};
o.P=n("");o.ca=function(){return this.a.video.duration};o.H=function(){return!this.B?M:this.a.Sd?"s4":this.a.paused?"s3":"s2"};o.X=function(){return this.a.video.time};o.T=n(-1);o.ba=l("Ya");o.Z=k();o.S=k();o.da=function(){return isNaN(this.q)?0:ra(this.q)};o.$=l("za");o.Q=l("ua");o.aa=n("FP");R.prototype.getStrategyName=R.prototype.aa;R.prototype.isReady=R.prototype.O;R.prototype.getTitle=R.prototype.J;R.prototype.getVideoPath=R.prototype.M;R.prototype.getContentType=R.prototype.U;
R.prototype.getAdPosition=R.prototype.P;R.prototype.getTotalDuration=R.prototype.ca;R.prototype.getState=R.prototype.H;R.prototype.getCurrentPlayTime=R.prototype.X;R.prototype.getBitrate=R.prototype.T;R.prototype.getThumbnailPath=R.prototype.ba;R.prototype.getPlayerType=R.prototype.Z;R.prototype.getAutoplayType=R.prototype.S;R.prototype.getViewStartTime=R.prototype.da;R.prototype.getSections=R.prototype.$;R.prototype.getAuthors=R.prototype.Q;R.verify=function(){return!!window.flowplayer};function T(a){this.a=a;this.qb=this.B=this.F=j;this.q=t();this.ua=this.za=d;this.ia()}o=T.prototype;o.ia=function(){this.a.readyState>0&&this.la();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.ha();this.a.addEventListener("canplay",u(this.la,this));var a=u(this.ha,this);this.a.addEventListener("playing",a);this.a.addEventListener("webkitbeginfullscreen",a);this.a.addEventListener("webkitendfullscreen",u(this.Ad,this))};o.la=function(){this.F=g};o.ha=function(){this.B=g;this.qb=j};
o.Ad=function(){this.qb=g};o.O=l("F");o.J=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};o.M=function(){return this.a.currentSrc||""};o.U=function(){return K};o.P=n("");o.ca=function(){return za(this.a.duration)};o.H=function(){return!this.B?M:this.a.ended||this.qb&&this.a.currentTime==this.a.duration?"s4":this.a.paused||this.qb?"s3":"s2"};o.X=function(){return za(this.a.currentTime)};o.T=n(-1);o.ba=function(){return this.a.poster||""};o.Z=k();
o.S=function(){return this.a.autoplay?"auto":"man"};o.da=function(){return ya(this.q)};o.$=l("za");o.Q=l("ua");o.aa=n("H5");T.prototype.getStrategyName=T.prototype.aa;T.prototype.isReady=T.prototype.O;T.prototype.getTitle=T.prototype.J;T.prototype.getVideoPath=T.prototype.M;T.prototype.getContentType=T.prototype.U;T.prototype.getAdPosition=T.prototype.P;T.prototype.getTotalDuration=T.prototype.ca;T.prototype.getState=T.prototype.H;T.prototype.getCurrentPlayTime=T.prototype.X;
T.prototype.getBitrate=T.prototype.T;T.prototype.getThumbnailPath=T.prototype.ba;T.prototype.getPlayerType=T.prototype.Z;T.prototype.getAutoplayType=T.prototype.S;T.prototype.getViewStartTime=T.prototype.da;T.prototype.getSections=T.prototype.$;T.prototype.getAuthors=T.prototype.Q;T.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==h;return b&&!a};function U(a){this.a=a;this.B=this.va=this.F=j;this.q=t();this.ia()}o=U.prototype;o.ia=function(){this.a.onReady(r(this.la,this));this.a.onTime(r(this.wd,this));this.a.onComplete(r(this.xd,this))};o.la=function(){this.F=g};o.wd=function(){this.va=j;if(!this.B)this.B=g};o.xd=function(){this.va=g};o.O=function(){this.a.getState();return this.F||this.a.getState()!==d};o.J=function(){var a=Xb(this);return!a?"":a.title};
function Xb(a){if(a.a.getPlaylistIndex===d)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return h;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?h:b[a]}o.M=function(){var a=Xb(this);return!a?"":a.file};o.U=function(){return K};o.P=n("");o.ca=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};o.H=function(){if(!this.B)return M;var a=this.a.getState();return this.va?"s4":a==="PAUSED"?"s3":"s2"};o.X=function(){return this.a.getPosition()};o.T=n(-1);
o.ba=function(){var a=Xb(this);return!a?"":a.image};o.Z=k();o.da=function(){return isNaN(this.q)?0:ra(this.q)};o.Q=k();o.$=k();o.S=n("unkn");o.aa=n("JW");U.prototype.getStrategyName=U.prototype.aa;U.prototype.isReady=U.prototype.O;U.prototype.getTitle=U.prototype.J;U.prototype.getVideoPath=U.prototype.M;U.prototype.getContentType=U.prototype.U;U.prototype.getAdPosition=U.prototype.P;U.prototype.getTotalDuration=U.prototype.ca;U.prototype.getState=U.prototype.H;U.prototype.getCurrentPlayTime=U.prototype.X;
U.prototype.getBitrate=U.prototype.T;U.prototype.getThumbnailPath=U.prototype.ba;U.prototype.getPlayerType=U.prototype.Z;U.prototype.getViewStartTime=U.prototype.da;U.prototype.getAuthors=U.prototype.Q;U.prototype.getSections=U.prototype.$;U.prototype.getAutoplayType=U.prototype.S;U.verify=function(a){return v(a.id)&&v(a.registerPlugin)};function V(a){this.a=a;this.Bc="";this.ja=M;this.wa=K;this.qa="";this.q=t();this.ia()}o=V.prototype;o.ia=function(){this.a.kBind("playerStateChange.cb",r(this.zd,this));this.a.kBind("playerUpdatePlayhead.cb",r(this.rd,this));this.a.kBind("playerPlayEnd.cb",r(this.yd,this));this.a.kBind("adStart.cb",r(this.ed,this));this.a.kBind("adEnd.cb",r(this.dd,this));this.a.kBind("switchingChangeComplete.cb",r(this.vd,this))};
o.zd=function(a){switch(a){case "playing":this.ja="s2";break;case "buffering":this.ja="s3";break;case "paused":this.ja="s3"}};o.rd=function(){this.ja="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};o.yd=function(){this.ja="s4"};o.ed=function(a){this.wa="ad";switch(a){case "pre":this.qa="a1";break;case "post":this.qa="a3";break;case "mid":this.qa="a2";break;case "main":this.qa="a5"}};o.dd=function(){this.wa=K};o.vd=function(a,b){this.Mc=b};
o.O=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=h};o.J=function(){return this.a.evaluate("{mediaProxy.entry.name}")};o.M=function(){if(!this.O())return this.Bc;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.Bc=a)||""};o.U=l("wa");o.P=l("qa");o.ca=function(){var a=this.a.evaluate("{duration}");return za(a)};o.H=l("ja");o.X=function(){var a=this.a.evaluate("{video.player.currentTime}");return za(a)};o.T=l("Mc");
o.ba=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};o.Z=k();o.S=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};o.da=function(){return isNaN(this.q)?0:ya(this.q)};o.$=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};
o.Q=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};o.aa=n("KT");V.prototype.getStrategyName=V.prototype.aa;V.prototype.isReady=V.prototype.O;V.prototype.getTitle=V.prototype.J;V.prototype.getVideoPath=V.prototype.M;V.prototype.getContentType=V.prototype.U;V.prototype.getAdPosition=V.prototype.P;V.prototype.getTotalDuration=V.prototype.ca;V.prototype.getState=V.prototype.H;V.prototype.getCurrentPlayTime=V.prototype.X;V.prototype.getBitrate=V.prototype.T;
V.prototype.getThumbnailPath=V.prototype.ba;V.prototype.getPlayerType=V.prototype.Z;V.prototype.getAutoplayType=V.prototype.S;V.prototype.getViewStartTime=V.prototype.da;V.prototype.getSections=V.prototype.$;V.prototype.getAuthors=V.prototype.Q;V.verify=function(a){return typeof a.kBind=="function"};function W(a){this.$b=d;this.a=a;this.jc=d;this.F=j;this.Ea=d;this.B=j;this.ua=this.za=this.q=d;this.$b=q.OO;this.jc=this.a.mb;this.q=t();this.ia()}o=W.prototype;
o.ia=function(){var a=this.jc,b=this.$b.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",r(this.la,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",r(this.gd,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",r(this.ha,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",r(this.fd,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",r(this.qd,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",r(this.ld,this))};o.la=function(){this.F=g};
o.gd=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.Ea=a===0?"a1":Yb(a,b)?"a3":"a2"};o.ha=function(){this.B=g};o.fd=function(){this.Ea=d};o.qd=k();o.O=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.F=g;return this.F};o.J=function(){var a=this.a.getItem();return a?a.title:""};o.M=function(){return(this.a.getItem()||{}).embedCode||this.a.embedCode||""};o.U=function(){return this.Ea===d?K:"ad"};
o.P=function(){return this.Ea?this.Ea:""};o.ca=function(){var a=this.a.getDuration();return a===-1||isNaN(a)?-1:a*1E3};o.H=function(){if(!this.B)return M;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return Yb(a,b)?"s4":"s2"};function Yb(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}o.ld=function(){this.Ea=d};
o.X=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};o.T=function(){return this.a.getTargetBitrate()};o.ba=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};o.Z=k();o.S=k();o.da=function(){return isNaN(this.q)?0:ya(this.q||0)};o.$=l("za");o.Q=l("ua");o.aa=n("OO");W.prototype.getStrategyName=W.prototype.aa;W.prototype.isReady=W.prototype.O;W.prototype.getTitle=W.prototype.J;W.prototype.getVideoPath=W.prototype.M;
W.prototype.getContentType=W.prototype.U;W.prototype.getAdPosition=W.prototype.P;W.prototype.getTotalDuration=W.prototype.ca;W.prototype.getState=W.prototype.H;W.prototype.getCurrentPlayTime=W.prototype.X;W.prototype.getBitrate=W.prototype.T;W.prototype.getThumbnailPath=W.prototype.ba;W.prototype.getPlayerType=W.prototype.Z;W.prototype.getAutoplayType=W.prototype.S;W.prototype.getViewStartTime=W.prototype.da;W.prototype.getSections=W.prototype.$;W.prototype.getAuthors=W.prototype.Q;
W.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("adPlaying")};function X(a){this.a=a;this.fa=h;this.ja=M;this.wa=K;this.qa="";this.q=t();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}o=X.prototype;o.$c=function(a){this.ia(a.controller)};
o.ia=function(a){a.addEventListener("OnLoadRelease",u(this.oc,this));a.addEventListener("OnLoadReleaseUrl",u(this.oc,this));a.addEventListener("OnReleaseStart",u(this.td,this));a.addEventListener("OnMediaPlay",u(this.nd,this));a.addEventListener("OnMediaStart",u(this.pd,this));a.addEventListener("OnMediaPause",u(this.Gb,this));a.addEventListener("OnMediaComplete",u(this.md,this));a.addEventListener("OnMediaError",u(this.Gb,this));a.addEventListener("OnMediaBuffer",u(this.Gb,this));a.addEventListener("OnMediaPlaying",
u(this.od,this))};o.oc=function(a){if(a.data&&a.data.pid&&a.data.title)this.fa=a.data};o.td=function(a){if(a.data.release&&a.data.release&&a.data.release.pid&&a.data.release.title)this.fa=a.data.release};o.nd=function(){this.ja="s2"};o.pd=function(a){this.ja="s2";a=a.data.baseClip;a.isAd?(this.wa="ad",this.qa=a.isMid?"a2":"a1"):(this.wa=K,this.qa="")};o.Gb=function(){if(this.ja!=M)this.ja="s3"};o.md=function(){this.ja="s4"};o.od=function(a){this.Qc=a.currentTime};o.O=function(){return this.fa!=h};
o.J=function(){return this.fa.title};o.M=function(){return!this.fa?"":this.fa.pid};o.U=l("wa");o.P=l("qa");o.ca=function(){return this.fa.duration};o.H=l("ja");o.X=l("Qc");o.T=function(){return this.fa.bitrate};o.ba=function(){return this.fa&&this.fa.defaultThumbnailUrl?this.fa.defaultThumbnailUrl:"http://link.theplatform.com/s/ngc/"+this.fa.pid+"?format=poster&height=70&width=95"};o.Z=k();o.S=k();o.da=function(){return isNaN(this.q)?0:this.q===d?0:t()-this.q};
o.$=function(){var a=this.fa.keywords?this.fa.keywords.split(","):[],b=[];s(this.fa.categories?this.fa.categories:[],function(a){b.push(encodeURIComponent(a.name))});s(a,function(a){b.push(encodeURIComponent(a.trim()))});return b};o.Q=k();o.aa=n("TP");X.prototype.initialize=X.prototype.$c;X.prototype.getStrategyName=X.prototype.aa;X.prototype.isReady=X.prototype.O;X.prototype.getTitle=X.prototype.J;X.prototype.getVideoPath=X.prototype.M;X.prototype.getContentType=X.prototype.U;
X.prototype.getAdPosition=X.prototype.P;X.prototype.getTotalDuration=X.prototype.ca;X.prototype.getState=X.prototype.H;X.prototype.getCurrentPlayTime=X.prototype.X;X.prototype.getBitrate=X.prototype.T;X.prototype.getThumbnailPath=X.prototype.ba;X.prototype.getPlayerType=X.prototype.Z;X.prototype.getAutoplayType=X.prototype.S;X.prototype.getViewStartTime=X.prototype.da;X.prototype.getSections=X.prototype.$;X.prototype.getAuthors=X.prototype.Q;X.verify=function(a){return typeof a.controller!=="undefined"};function Zb(a,b){this.a=a;this.yc=b;this.Ga=window.location!=window.parent.location;this.sc=j;this.Hd=t();this.xc="_v_";this.sa={};G.call(this)}ea(Zb,G);var $b=q.QUICK_TEST?1E4:6E4,ac="autoDetect",bc={Pd:"title",Qd:"videopath",Od:"thumbnailpath"},cc={};o=Zb.prototype;
o.N=function(){this.Db=(this.Ja=this.G.D("_chartbeat3"))?0:1;this.Wb=this.Mb=g;this.vb=j;this.jb=this.Kb=this.bc=this.Ca=d;this.Pa=15E3;this.$a=d;this.Cd=this.Sb=this.Tb=this.ab=this.bb=0;var a=q.location;this.vc=j;if(!this.Ja||this.Ja.length===0)this.Ja=ga(Fb(this),3);this.G.create("_chartbeat3",this.Ja,2592E3);var b;(b=this.yc)&&ma(b)?(this.ea=new b(this.a),b=g):b=j;if(b){y(this.k,"pingServer","ping.chartbeat.net");y(this.k,"title",document.title);y(this.k,"domain",a.hostname);y(this.k,"path",yb(!!this.k.useCanonical));
this.ea.getPlayerType&&y(this.k,"video_type",this.ea.getPlayerType());this.bc=setInterval(u(this.Nc,this),1E3);if(this.Ga===g)this.fb=u(this.Xc,this),w(window,"message",this.fb),this.$a=setInterval(this.Dd,1E3);Zb.pa.N.call(this)}};o.sb=k();
o.ka=function(){if(this.ea){if(!dc(this))this.Wb=g;if(!this.Wb)return t()-this.Ba>=this.Ua&&clearInterval(this.Ca),Zb.pa.ka.call(this);if(this.ea.isReady())this.vb=this.Wb=j,this.Kb=ec(this),fc(this),this.Ca=setInterval(u(this.ub,this),100),Zb.pa.ka.call(this);else if(!this.vb){this.vb=g;if(this.Cd++>150)throw"Error: Video strategy never reported its ready state";clearInterval(this.ya);this.ya=setInterval(u(this.ka,this),100)}}};
o.Ka=function(){if(this.ea){var a=this.k,b=this.ea,c=b.getState(),e=dc(this),f=this.Ga?[]:q._cbq||(q._cbq=[]),i=b.getViewStartTime(),p=gc(this),C=b.getAutoplayType?b.getAutoplayType():d,i=i===-1?-1:i/1E3,p=p?encodeURIComponent(p):d;if(!cc.path||cc.path===e||c==="s2"&&cc.state!=="s2")switch(cc={path:e,state:c},f.push(["_vi",oa(hc(this))]),f.push(["_vp",e]),f.push(["_vdd",encodeURIComponent("video@"+(a.videodomain||a.domain))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",b.getContentType()]),
b.getAdPosition&&f.push(["_vap",b.getAdPosition()]),f.push(["_vtn",oa(gc(this))]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case M:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=ic(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",i)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",p)+Z("_vaup",C||"unkn")+Z("_vplt",a.video_type)+Z("_vce",this.Sb)+Z("c",Math.round(ra(this.Hd)/
600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.Tb+"&j="+(this.Pa/1E3+15)+jc(this)+"&tz="+(new Date).getTimezoneOffset()+(xb(this.G)?"&l=1":"")+"&_";this.Ga===g&&s(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.Xa(a)}};function Z(a,b){return b!==d&&b!==""?"&"+a+"="+b:""}o.Va=function(){this.G.update("_cb_cp",this.La,3600,j,",")};function jc(a){var b=a.G.D("_cb_cp");a.G.remove("_cb_cp");return b?"&D="+b:""}
function kc(a){return a.k.subdomain?a.k.subdomain:ja(q.location.hostname)}function dc(a){var b=a.sa.videopath;if(b)return b;if(a.k.videoPathHash){if(a=hc(a))return ga(a)}else return a.ea.getVideoPath();return""}function hc(a){return a.sa.title||a.ea.getTitle()}function gc(a){return a.sa.thumbnailpath||a.ea.getThumbnailPath()}
function ic(a){var b=a.k,c=a.ea,e=q.location,f=c.getUid&&c.getUid()||b.uid,i=b.videodomain||c.getHost&&c.getHost()||b.domain,i=encodeURIComponent("video@"+i),p="",C=a.Wa?"&b="+a.Wa:"",m;m=a.k.path;m=a.k.useSubDomains!==j&&m&&m.substr(0,1)==="/"?kc(a)+m:m;var L=c.getSections&&c.getSections(),H=c.getAuthors&&c.getAuthors(),P=b.sections?"&g0="+encodeURIComponent(b.sections):"",S=b.authors?"&g1="+encodeURIComponent(b.authors):"",L=L===d||b.videoPageGroups?P:"&g0="+L.join(","),H=H===d||b.videoPageGroups?
S:"&g1="+H.join(","),S="",P=dc(a);if(a.jb===d)a.jb=P;else if(P!=a.jb)S=Z("D",a.La),a.La=ga(Fb(a)),a.jb=P,a.bb=0,a.ab=0,a.Tb=0,a.Sb=0,a.Mb=g;if(a.Mb||S){if(a.Ga===j||a.Ga===g&&a.sc===g)a.Mb=j;p=(Ib(a)?"&v=":"&r=")+Jb(a)}a.Tb+=a.bb;a.bb=0;a.Sb+=a.ab;a.ab=0;fc(a);var ba=P="",Y="",N="";if(!a.Ga===g||a.vc===g)P="&_vi="+Kb(a),ba="&_vp="+encodeURIComponent(m),Y="&_vh="+oa(kc(a)),N="&_vdd="+encodeURIComponent(b.domain);m=!b.noCookies&&a.G.isSupported();var I=c.getStrategyName?c.getStrategyName():"";return(e.protocol||
"http:")+"//"+b.pingServer+"/ping?h="+i+"&g="+f+"&p="+oa(dc(a))+"&i="+hc(a)+L+H+"&u="+a.Ja+"&t="+a.La+"&x=0&y=0&V=61"+Z("VS",I)+(m?"&n="+a.Db:"&nc=1")+C+p+S+Z("_vd",c.getTotalDuration())+P+ba+Y+N}o.ub=function(){var a=ec(this);if(this.Kb!=a)this.Kb=a,fc(this),this.ka()};function fc(a){var b=a.Pa;a.Pa=lc(a)===g?5E3:a.ea.getState()===M?$b:15E3;if(b!=a.Pa)b=a.Pa,clearInterval(a.ya),a.ya=setInterval(u(a.ka,a),b)}function ec(a){return a.ea.getState()+a.ea.getAdPosition()}
function lc(a){return a.ea.getState()==="s2"||a.ea.getAdPosition()!==""&&a.ea.getViewAdPlayTime!==-1}o.Nc=function(){lc(this)===g&&(this.bb+=1,this.ea.getContentType()===K&&(this.ab+=1))};o.Dd=function(){window.parent.postMessage("cbdata?","*")};
o.Xc=function(a){if(a.source===window.parent){var b=a.data;if(a.data.indexOf("domain=")===0){this.vc=g;var c={domain:g,uid:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g},e=this;s(b.split("&"),function(a){var a=a.split("="),b=a[0],a=a[1];c[b]&&(e.k[b]=decodeURIComponent(a))});ka(window,"message",this.fb);clearInterval(this.$a);this.$a=d;this.sc=g;this.ka()}}};o.setProperty=function(a,b){var c=j,e=this;s(bc,function(f){if(a.toLowerCase()==f)return e.sa[f]=b,c=g,j});return c};
o.terminate=function(){clearInterval(this.bc);clearInterval(this.$a);clearInterval(this.Ca);ka(window,"message",this.fb);Zb.pa.terminate.call(this)};o.xa=function(){Zb.pa.xa.call(this);this.yc=this.a=this.fb=h};function $(a){this.a=a;this.F=g;this.B=j;this.q=t();this.Ca=this.ua=this.za=d;this.Cc=q._sf_async_config.ytApikey;this.Oa=d;mc(this,nc(this));this.ia()}o=$.prototype;o.ia=function(){this.Ca=setInterval(r(this.ub,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.ha()};o.ub=function(){if(this.a.getPlayerState()===1)clearInterval(this.Ca),this.Ca=d,this.ha()};o.la=function(){this.F=g};o.ha=function(){if(!this.B)this.B=g};
function nc(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}function mc(a,b){var c="https://www.googleapis.com/youtube/v3/videos?part=snippet&id="+b+"&key="+a.Cc,e=u(function(){this.Oa={id:b,title:""}},a);if(a.Cc){var f=u(function(a){if(b==nc(this))a?a.error?e():this.Oa={id:b,title:a&&a.items&&a.items[0]&&a.items[0].snippet&&a.items[0].snippet.title||""}:e()},a);sa(c,f)}else e()}o.O=function(){return this.F&&!!this.Oa};
o.J=function(){return this.Oa&&this.Oa.id===nc(this)?this.Oa.title:""};o.M=function(){return nc(this)||this.a.getVideoUrl()};o.U=function(){return K};o.P=n("");o.ca=function(){var a=this.a.getDuration();return x(a)?a*1E3:a};o.H=function(){if(!this.B)return M;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};o.X=function(){return this.a.getCurrentTime()};o.T=n(-1);o.ba=function(){return"http://img.youtube.com/vi/"+nc(this)+"/default.jpg"};o.Z=k();o.S=k();
o.da=function(){return isNaN(this.q)?0:ra(this.q)};o.$=l("za");o.Q=l("ua");o.aa=n("YT");$.prototype.getStrategyName=$.prototype.aa;$.prototype.isReady=$.prototype.O;$.prototype.getTitle=$.prototype.J;$.prototype.getVideoPath=$.prototype.M;$.prototype.getContentType=$.prototype.U;$.prototype.getAdPosition=$.prototype.P;$.prototype.getTotalDuration=$.prototype.ca;$.prototype.getState=$.prototype.H;$.prototype.getCurrentPlayTime=$.prototype.X;$.prototype.getBitrate=$.prototype.T;
$.prototype.getThumbnailPath=$.prototype.ba;$.prototype.getPlayerType=$.prototype.Z;$.prototype.getAutoplayType=$.prototype.S;$.prototype.getViewStartTime=$.prototype.da;$.prototype.getSections=$.prototype.$;$.prototype.getAuthors=$.prototype.Q;$.verify=function(a){return ma(a.getDuration)&&ma(a.getVideoUrl)&&ma(a.getVideoEmbedCode)};function oc(){q._cbv_strategies||(q._cbv_strategies=[]);q._cbv_strategies.push(W);q._cbv_strategies.push(T);q._cbv_strategies.push(R);q._cbv_strategies.push($);q._cbv_strategies.push(U);q._cbv_strategies.push(Q);q._cbv_strategies.push(O);q._cbv_strategies.push(V);q._cbv_strategies.push(X);this.Ub=[];this.sa=[];this.k=q._sf_async_config||{};Ma("_cbv",u(this.Yc,this));this.k[ac]!==j&&pc()}
oc.prototype.Yc=function(a){if(aa(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){qc();return}else if(b==="removePlayer"){rc(this,a[1]);return}else if(b==="setProps"){sc(a[1])||this.sa.push(a[1]);return}}tc(this,a)};function tc(a,b){var c=j,e=q._cbv_strategies;v(window.jwplayer)&&(b=ma(b)?b():b);s(e,function(a){if(a.verify(b)===g)return c=a,j});c===j||uc(a,b,c)}
function rc(a,b){var c=a.Ub,e=q.pSUPERFLY_video,f=pa(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=pa(e,function(a){return a.a===b});f!==-1&&e.splice(f,1)[0].xa()}function sc(a){if(!v(a))return j;var b=a.player,c=qa(function(a){return a.a===b});return!v(c)?j:vc(c,a)}function vc(a,b){var c=j;s(b,function(b,f){if(f!=="player"&&(c=a.setProperty(f,b),!c))return c});return c}
function uc(a,b,c){var e=j;s(a.Ub,function(a){if(b===a)return e=g,j});if(!e){c=new Zb(b,c);q.pSUPERFLY_video.push(c);for(var f=a.sa.length-1;f>-1;f--)vc(c,a.sa[f])&&a.sa.splice(f,1);Gb(c);a.Ub.push(b)}}
function pc(){if(ma(window.jwplayer)&&v(window.jwplayer()))for(var a=0,b=window.jwplayer(a);v(b.id);)window._cbv.push(b),b=window.jwplayer(++a);else window.flowplayer?window._cbv.push(window.flowplayer):window.brightcove?window._cbv.push(window.brightcove):window.videojs?(a=Qa("data-account","video"),a.length==0&&(a=Qa("data-account","div")),s(a,function(a){var b=window.videojs(a.getAttribute("id"));b&&(window.videojs.plugin("chartbeat",function(a){b.cb_configs=a}),window._cbv.push(b))})):window.kWidget?
window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))}):window.$pdk?window._cbv.push(window.$pdk):s(document.getElementsByTagName("video"),function(a){window._cbv.push(a)})}
function qc(){function a(){function a(b){q._cbv.push(b.target)}var b=q.YT.Player;s(document.getElementsByTagName("iframe"),function(f){var i=f.src,p=i&&i.indexOf("www.youtube.com/embed/");i&&p>=0&&p<9&&new b(f,{events:{onReady:a}})})}if(q.YT&&q.YT.Player)a();else{var b=q.onYouTubeIframeAPIReady;q.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(q,arguments)}catch(c){}a()}}}};if(window.location==window.parent.location&&!q.pSUPERFLY){var wc=new J;q.pSUPERFLY={virtualPage:u(wc.Ld,wc),activity:u(wc.Gc,wc)};Gb(wc);var xc=z.Y(g);if(xc)if(xc.getItem("_cb_ip")){var yc=q.location;(!/^(.+[.])?chartbeat\.com$/.test(yc.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(yc.pathname))||db()}else w(q,"message",eb)}q.pSUPERFLY_video||(q.pSUPERFLY_video=[]);new oc;function zc(){v(q._cb_shared)||(q._cb_shared={});return q._cb_shared};function Ac(){var a=q.location.href,a=a.replace(/-{2,}/g,"-"),a=Ka(a);a.pathname=Ab(a.pathname);return a}function Bc(a){var b=E.D("_chartbeat6");if(!b)return h;var b=b.split("::"),c,e;if(b.length===1)c=b[0].split(","),e=0;else{var f,i=Ac(),p=La(i);s(b,function(a,b){var i=a.split(","),H=xa(p,decodeURIComponent(i[0]));if(H===0)return c=i,e=b,j;if(f===d||H<f)f=H,c=i,e=b})}b.splice(e,1);a="_chartbeat6="+b.join("::")+Cc(a);document.cookie=a;return{Rd:c[0],Rc:c[1],Kd:c[2],origin:c[3]}}
function Cc(a){var b="",c;if(!(a&&a.constructor===Object))return b;a.lc&&(c=new Date,c.setTime(c.getTime()+a.lc),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function Dc(a,b){if(a===b)return g;for(var c=b.split("."),e=a.split(".");c.length;){if(e.length===0)return j;if(c.pop()!==e.pop())return j}return g};function Ec(){this.xc="_t_";G.call(this)}ea(Ec,G);o=Ec.prototype;
o.N=function(){Ec.pa.N.call(this);Na(this.k);var a=q.location;y(this.k,"mabServer","mabping.chartbeat.net");y(this.k,"title",document.title);y(this.k,"domain",a.hostname);y(this.k,"path",yb(!!this.k.useCanonical));this.ra=ja(a.hostname);this.k.domain=ja(this.k.domain);var b=this.k,a=b.topStorageDomain,b=b.domain,c=q.location.hostname;this.Id=a?a:Dc(c,b)?b:c.replace(/^www\./,"");this.Ac=this.dc=this.ec="";this.cb=this.Bb=j;a=Bc({domain:"."+this.Id,lc:6E4,path:"/"});if(a!==h)this.ec=a.origin,this.dc=
a.Rc,this.Ac=a.Kd,this.Bb=g;this.Ua=6E4;this.mc=0;a=u(this.Zc,this);b=zc();for(b=(v(d)&&!v(b.m)?d:b.m)||[];b.length;)a(b.shift());a={push:a};zc().m=a};o.Ka=function(){var a=this.ma.Ma,b=Fc(this),c,e,f;if(this.Bb)c=this.ec,e=this.dc,f=this.Ac,this.Xa(b+"&x="+e+"&v="+f+"&xo="+c+"&e="+a);!this.cb&&v(this.zc)&&Gc(this,this.zc);this.cb=g};o.kb=function(){var a=q._sf_startpt,b=q._sf_endpt;if(x(a))this.Wa=x(b)?b-a:t()-a;D.N();if(this.Bb)this.ya=q.setInterval(u(this.ka,this),500);this.ka()};
o.ka=function(){var a,b;this.cb?(a=this.ma.Ma,b=this.mc*15,a-b>=15&&(this.Ka(),this.mc+=1),a>=45&&q.clearInterval(this.ya)):this.Ka()};function Fc(a){var b=a.k;return(q.location.protocol||"http:")+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.ra)+"&u="+a.ob+"&c="+Math.round((t()-a.Ba)/600)/100}o.Va=k();
o.Gd=function(a){var b=a.d,c=h;b!==h&&(c={Ob:b.s,ad:b.l,kc:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.cb?Gc(this,a):this.zc=a};function Gc(a,b){var c=Fc(a),e=b.status,f=b.data;if(e=="s"&&f!==h){if(!f.ad){var i=u(a.Xa,a);f.Ob&&f.Ob.constructor===Object&&s(f.Ob,function(a,b){i(c+"&x="+b+"&v="+a+"&e=-1")});Object.prototype.toString.call(f.kc)==="[object Array]"&&s(f.kc,function(a){i(c+"&mt=e&me=3&x="+a)})}}else e=="e"&&a.Xa(c+"&mt=e&me="+b.code)}
o.Zc=function(a,b){for(var c=0,e=arguments.length;c<e;c++)a=arguments[c],a.shift()==="t"&&this.Gd.apply(this,a)};if(!q.pSUPERFLY_mab)q.pSUPERFLY_mab={},Gb(new Ec);})();
